services:
    # The main container must be specifically named "app"
    app:
        image: ghcr.io/victoralvesf/aonsoku-podcasts:latest
        container_name: aonsoku_podcasts
        depends_on:
            mysql:
                condition: service_healthy
        command: [ "sh", "./aonsoku.sh", "start" ]

    nginx:
        image: nginx:alpine
        container_name: aonsoku_podcasts_nginx
        ports:
            - "6060:80" # You can use any port other than 6060
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8
        container_name: aonsoku_podcasts_db
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 0s

    queue:
        image: ghcr.io/victoralvesf/aonsoku-podcasts:latest
        container_name: aonsoku_podcasts_queue
        depends_on:
            - app
        command: [ "sh", "./aonsoku.sh", "queue" ]

    scheduler:
        image: ghcr.io/victoralvesf/aonsoku-podcasts:latest
        container_name: aonsoku_podcasts_scheduler
        depends_on:
            - app
        command: [ "sh", "./aonsoku.sh", "scheduler" ]

volumes:
    mysql_data:
