services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        image: aonsoku_podcasts
        container_name: aonsoku_podcasts
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - .env
        command: [ "sh", "./aonsoku.sh", "start" ]

    nginx:
        image: nginx:alpine
        container_name: aonsoku_podcasts_nginx
        ports:
            - "6060:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8
        container_name: aonsoku_podcasts_db
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=eiYnEFIZkoug5z292J7isfMfQId3R9SBuAM
        volumes:
            - mysql_data:/var/lib/mysql
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent" ]
            interval: 5s
            timeout: 3s
            retries: 5
            start_period: 0s

    queue:
        image: aonsoku_podcasts
        container_name: aonsoku_podcasts_queue
        env_file:
            - .env
        depends_on:
            - app
        command: [ "sh", "./aonsoku.sh", "queue" ]

    scheduler:
        image: aonsoku_podcasts
        container_name: aonsoku_podcasts_scheduler
        env_file:
            - .env
        depends_on:
            - app
        command: [ "sh", "./aonsoku.sh", "scheduler" ]

volumes:
    mysql_data:
