version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: aonsoku_podcasts
        working_dir: /var/www/html
        depends_on:
            - mysql
        env_file:
            - .env.production
        command: |
            bash -c "php artisan migrate --force && php-fpm"

    nginx:
        image: nginx:alpine
        container_name: aonsoku_podcasts_nginx
        ports:
            - "6060:80"
        volumes:
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    mysql:
        image: mysql:8
        container_name: aonsoku_podcasts_db
        env_file:
            - .env.production
        volumes:
            - mysql_data:/var/lib/mysql

    queue:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: aonsoku_podcasts_queue
        working_dir: /var/www/html
        env_file:
            - .env.production
        depends_on:
            - app
        command: php artisan queue:work

    scheduler:
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
        container_name: aonsoku_podcasts_scheduler
        working_dir: /var/www/html
        env_file:
            - .env.production
        depends_on:
            - app
        command: sh -c "while true; do php artisan schedule:run --verbose --no-interaction; sleep 60; done"

volumes:
    mysql_data:
